[tool.poetry]
name = "chess"
version = "0.1.0"
description = ""
authors = ["virashu <svladichek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyqt6 = "^6.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
